//
//  ViewController.swift
//  iosQuiz
//
//  Created by Stacey Abbott on 11/1/17.
//  Copyright © 2017 Stacey Abbott. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    //outlets
    @IBOutlet weak var questionLabel: UILabel!
    @IBOutlet weak var answerLabel: UILabel!
    
    var currentQuestion = 0 //start a count so we can iterate through each of the questions
    
        
        let quizBank = [
            ("What is the first step of iOS development?", "Create the user interface. As we create the UI, we will get a better understanding of our application. Then we breath life into our application."),
            ("Why do we use Autolayout?", "We use Autolayout to set constraints on our View objects so that it can adapt to different screen sizes and to different orientations (portrait or landscape)"),
            ("What is the difference between IBAction and IBOutlet?", "Both IBAction and IBOutlets are connections from View elements on our storyboard. IBOutlet connects a proprety in our code to an object in a storyboard while an IBAction connects an event generated by an object in a storyboard to a method in our code."),
            ("What is the Model in MVC responsible for?", "Model objects are responsible for the data of our application. It is important to note that Model objects know nothing about the user interface. An example of a Model could be a list of questions and answers."),
            ("What is the View in MVC responsible for?", "View objects are objects that can be seen by the user (objects you drag into the storyboard). Some examples are labels and buttons."),
            ("What is the Controller in MVC responsible for?", "Controller objects facilitate the communication between the Model and the View since the Model and the View should never directly talk to each other (remember the Model knows nothing about the user interface).")
        ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        updateUI() //add an update function for everytime we go to a new question
    }
    
    func updateUI() {
        questionLabel.text = quizBank[currentQuestion].0 //question is at the zero index of wherever the question count is now
        answerLabel.text = quizBank[currentQuestion].1 //answer is at the one index of wherever we're at now
        answerLabel.isHidden = true //answer label is hidden until we click the answer button
    }
    
    
    //actions
    @IBAction func answerButton(_ sender: UIButton) {
        if answerLabel.isHidden == true {
            answerLabel.isHidden = false
        }else{
            answerLabel.isHidden = true
        }
    }
    
    @IBAction func nextButton(_ sender: UIButton) {
        if currentQuestion != quizBank.count - 1 { //as long as were not past the last question...
            currentQuestion += 1 //move the question up by one
        }else{
            currentQuestion = 0
        }
        
        updateUI()
    }
    
 
    
    
}


